### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by HsuTimothy** [mseminatore/TeslaJS#118]
**Describe the bug**
When attempting to login I run into a CORS issue.

`Access to fetch at 'https://owner-api.teslamotors.com/oauth/token' from origin 'http://hsutimothy.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Steps To Reproduce**
```
tjs.login(this.state.email, this.state.password, function (err, result) {
      if (result.error) {
        console.log(JSON.stringify(result.error));
        process.exit(1);
      }

      var token = JSON.stringify(result.authToken);

      if (token)
        console.log("Login Succesful!");
    });
```

**Expected behavior**
Get auth token

What is the workaround this if any? Thanks for your help!

**Comment by mseminatore** [comment]
@HsuTimothy Can you provide more context on this issue and how you are trying to use the library?  Does the login sample not work?  Are you using this library within a web page for example?

**Comment by HsuTimothy** [comment]
Hi @mseminatore, sorry I should've been more specific. 

Yes, I am trying to use this library within a web page. Specifically, a reactjs web-project.

**Comment by mseminatore** [comment]
The library has been successfully used both as pure NodeJS web apps as well as ExpressJS-based web-pages without CORS issues.  I am not familiar with ReactJS.  You may want to research how to enable cross origin calls for ReactJS-based sites.  This may help: https://stackoverflow.com/questions/38822317/cors-in-react-js

**Comment by dacastro4** [comment]
@HsuTimothy did you solve the CORS issue? Tesla API doesn't allow `options`

**Comment by jrreich** [comment]
@dacastro4 @HsuTimothy @mseminatore 
Has anyone solved this? From what I've read there are a few workarounds, but the only real way to fix it is to set up a proxy.

**Comment by mseminatore** [comment]
@jrreich I closed this issue about a year ago since as far as I can tell the issue is not with the library but the use-case.
