### ISSUE TITLE
PRs to implement Solar APIs?

### ISSUE THREAD

**Issue by geekdave** [mseminatore/TeslaJS#134]
Thanks for this project!  I don't have a Tesla vehicle, but I do have Tesla solar panels.  Wondering if you'd be open to some PRs to add these missing apis:

https://www.teslaapi.io/energy-sites/state-and-settings

I've got some working locally already -- just wondering whether to fork/augment this project or contribute directly.  Thanks again!

**Comment by mseminatore** [comment]
Sure! I am open to PR's for solar. It is something that I've wanted to do but I don't have the solar panels :)

**Comment by geekdave** [comment]
🎉 Awesome!  PRs coming soon...

**Comment by mseminatore** [comment]
Please be sure to add/update docs. And if you are familiar with apiary you can update the API definition and add test cases.

**Comment by geekdave** [comment]
Thanks @mseminatore - Any idea why I'd be getting a 429 "Too Many Requests" error on some of the tests?  Seems to happen on 19 tests but the rest pass. 

$ node -v
v12.9.1
$ npm -v
6.10.2
$ export TESLAJS_SERVER=http://private-111a5-teslajs.apiary-mock.com
$ export TESLAJS_STREAMING=http://private-111a5-teslajs.apiary-mock.com
$ export TESLAJS_LOG=1
$ npm ci
$ npm test

```
  167 passing (20s)
  19 failing

  1) TeslaJS
       #mediaVolumeDownAsync()
         should succeed:
     Error: the string "Error response: 429" was thrown, throw an Error :)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at /Users/dcadwallader/dev/forks/TeslaJS/node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)
      at processTicksAndRejections (internal/process/task_queues.js:75:11)

[snip]
```

**Comment by mseminatore** [comment]
To protect their servers from DOS attacks many sites will throttle request rates. This suggests that the tests are calling apiary too quickly. I am not sure if there is a way to slow down requests in Mocha

**Comment by mseminatore** [comment]
@geekdave Any updates on progress? Still getting 429 issues?

**Comment by mseminatore** [comment]
@geekdave Is this something you are still planning to work on or should I close this down? I see from GitHub it looks like you may have something started.

**Comment by mseminatore** [comment]
@geekdave is this something that you are still working or shall I close this out?

**Comment by geekdave** [comment]
@mseminatore finally got around to wrapping this up... let me know if any changes are needed!
