### ISSUE TITLE
how to use TESLAJS_SERVER

### ISSUE THREAD

**Issue by Baha2Odeh** [mseminatore/TeslaJS#161]
how to use TESLAJS_SERVER? 

what it should help me to do? 

can use it to access my car without using the tesla email and password?

**Comment by mseminatore** [comment]
@Baha2Odeh The `TESLAJS_SERVER` environment variable allows you to override the default URI for the Tesla.com servers. This is useful, among other things, for testing where you might want, for example, to run your own mock of the Tesla servers.
