### ISSUE TITLE
VIN decode is incorrect for year

### ISSUE THREAD

**Issue by JonMurphy** [mseminatore/TeslaJS#188]
**Describe the bug**
VIN decode is incorrect for year for my Model Y.  VIN decode displays 2021

**Expected behavior**
vehicle.vin.charCodeAt(9) = L : this should equal year 2020

https://github.com/mseminatore/TeslaJS/blob/master/teslajs.js#L239

I believe the letter "I" (eye) is skipped.  I would guess the letter "O" (oh) would be skipped also.

**Library version**
branch: Master

**Comment by JonMurphy** [comment]
extra info:

MY2020 VIN DECODER
https://vpic.nhtsa.dot.gov/mid/home/displayfile/c646fbf1-8ba5-4575-af1e-f415a1131337

PDF of above:
[MY2020_VIN Decoder_S3XY.pdf](https://github.com/mseminatore/TeslaJS/files/4833916/MY2020_VIN.Decoder_S3XY.pdf)

**Comment by mseminatore** [comment]
Congrats on your Model Y! And thank you for bringing this to my attention. I had been planning to update once the VIN format for the model Y was documented.

**Comment by JonMurphy** [comment]
Thanks!  Let me know if I can help test!

**Comment by mseminatore** [comment]
@JonMurphy I believe I've now fixed this, can you test and LMK?
