### ISSUE TITLE
Scheduled Departure

### ISSUE THREAD

**Issue by fniewijk** [mseminatore/TeslaJS#194]
I'd like to control the Scheduled Departure setting and I'd love to have this functionality added

The Scheduled Departure feature is currently preventing my smart charging app from working perfectly, because I'm manually sending ON and OFF commands to the charger and this feature seems to interfere with it.

I don't have a Tesla right now to find the endpoints and document it unfortunately. But if someone can supply this, I would be more than happy to open a PR with the functionality.

**Comment by DoctorMcKay** [comment]
Scheduled departure is not controllable via the API.

**Comment by mseminatore** [comment]
@fniewijk, @DoctorMcKay is correct, this capability is not currently exposed through the API for mobile devices. For the Tesla Control app, in the Alerts screen I provide a way for you to schedule charge start/stop as a way to approximate this capability.
