### ISSUE TITLE
Is streamingColumns now incorrect

### ISSUE THREAD

**Issue by IMgoRt** [mseminatore/TeslaJS#198]
Line 1816 returns the expected column definition for the return from the streaming API, however, this now appears to be outdated.

Current setting:
`exports.streamingColumns = ['elevation', 'est_heading', 'est_lat', 'est_lng', 'est_range', 'heading', 'odometer', 'power', 'range', 'shift_state', 'speed', 'soc'];`

Current returned data (I cater for the timestamp within my code):

```
1596284941164,8,31415.7,45,106,290,51.248851,-1.115054,-1,D,158,127,257
1596284942165,7,31415.7,45,106,316,51.248870,-1.115092,-0,D,158,127,303
1596284942915,6,31415.7,45,106,343,51.248897,-1.115107,1,D,158,127,303
```

**Library version**
2.1.49

**Additional context**
Above data run against an SP100D manufactured in late '16 with HW2.0

**Comment by mseminatore** [comment]
@IMgoRt Here is the format of the data returned for my 2013 P85.

`1605212558278,128,95,<lat>,<long>,104,95,64156.4,0,128,,,50`

That looks to me like the columns as reported by the sample:

`Columns: timestamp,elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc`

When you say library version are you referring to the TeslaJS version? If so TJS is now at V4.94.

**Comment by IMgoRt** [comment]
> @IMgoRt Here is the format of the data returned for my 2013 P85.
> 
> `1605212558278,128,95,<lat>,<long>,104,95,64156.4,0,128,,,50`
> 
> That looks to me like the columns as reported by the sample:
> 
> `Columns: timestamp,elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc`
> 
> When you say library version are you referring to the TeslaJS version? If so TJS is now at V4.94.

That was early days, I think I quoted a nodered version rather than TJS.
I'm not sure if the format returned by Tesla as streaming isn't working at the moment.
Anyway I put a simple trap in based on mileage to flip the structure on each message as required.

**Comment by IMgoRt** [comment]
> @IMgoRt Here is the format of the data returned for my 2013 P85.
> 
> `1605212558278,128,95,<lat>,<long>,104,95,64156.4,0,128,,,50`
> 
> That looks to me like the columns as reported by the sample:
> 
> `Columns: timestamp,elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc`
> 
> When you say library version are you referring to the TeslaJS version? If so TJS is now at V4.94.

I quoted the version on the right of the code page which links to this:

https://github.com/mseminatore/TeslaJS/releases/tag/V2.1.49

**Comment by IMgoRt** [comment]
> > @IMgoRt Here is the format of the data returned for my 2013 P85.
> > `1605212558278,128,95,<lat>,<long>,104,95,64156.4,0,128,,,50`
> > That looks to me like the columns as reported by the sample:
> > `Columns: timestamp,elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc`
> > When you say library version are you referring to the TeslaJS version? If so TJS is now at V4.94.
> 
> That was early days, I think I quoted a nodered version rather than TJS.
> I'm not sure if the format returned by Tesla as streaming isn't working at the moment.
> Anyway I put a simple trap in based on mileage to flip the structure on each message as required.

OK, so I now log when the data is in the incorrect format - it appears to be incorrect when the vehicle is falling alseep (ShiftState null, locked, DriverNotPresent...), but correct at other times

**Comment by mseminatore** [comment]
Not sure that there is any additional work here since it works when the car is awak.

**Comment by IMgoRt** [comment]
> Not sure that there is any additional work here since it works when the car is awak.

OK, that's a bit strange - you acknowledge an issue but close the ticket.
I don't use the streaming API when vehicles is asleep/offline.
I see the issue whilst driving.

I code round the issue.

**Comment by mseminatore** [comment]
Your last statement, on 29 Nov was:

>OK, so I now log when the data is in the incorrect format - it appears to be incorrect when the vehicle is falling alseep (ShiftState null, locked, DriverNotPresent...), but correct at other times

I interpreted that to mean that the API was working correctly. I think what you perhaps meant to also say was that you believe the data returned does not match the streaming column order defined by the array. Is that a correct restatement of your issue?

If so, the input array is an unordered list - it is a `set`. Tesla does not interpret it as a request for the order in which columns are returned. And since the data returned by Tesla is not labeled, I make no attempt to guess at the values and re-order the returned array to match the input `set`.

**Comment by IMgoRt** [comment]
> Your last statement, on 29 Nov was:
> 
> > OK, so I now log when the data is in the incorrect format - it appears to be incorrect when the vehicle is falling alseep (ShiftState null, locked, DriverNotPresent...), but correct at other times
> 
> I interpreted that to mean that the API was working correctly. I think what you perhaps meant to also say was that you believe the data returned does not match the streaming column order defined by the array. Is that a correct restatement of your issue?
> 
> If so, the input array is an unordered list - it is a `set`. Tesla does not interpret it as a request for the order in which columns are returned. And since the data returned by Tesla is not labeled, I make no attempt to guess at the values and re-order the returned array to match the input `set`.

OK, yes that would be a more correct problem statement.
So your documentation could be updated to state 'normal' format and additional format - all I do is look to see if the value in .odometer is below 300 and flip columns for subsequent processing.

**Comment by mseminatore** [comment]
OK sorry, now I feel confused so please can you elaborate a little bit further. What do you mean about flipping columns when the `odometer` is below 300?

**Comment by IMgoRt** [comment]
> OK sorry, now I feel confused so please can you elaborate a little bit further. What do you mean about flipping columns when the `odometer` is below 300? Are you saying that Tesla returns a different column ordering based on mileage?

So normally tesla returns columns is the order:
speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading
So I load the values into an array with those labels

However, it frequently returns them in this order:
elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc

So if I interrogate the value in odometer and it is below 300 then it can't be my actual odo reading and must therefore be a heading, so I load the values into an array with the correct labels and then proceed with my code.

Obviously, this only works for vehicles that have covered more than 300 miles (I know of 2 cars for sale in the UK over 2 years old with less than 300 miles on the clock!)

**Comment by mseminatore** [comment]
Ok, thank you for explaining further. Is this behavior always tied to the `odometer` value? I can't test myself against a low mileage vehicle.

If you want to put together a PR to address this I can review/merge it in.

**Comment by IMgoRt** [comment]
> Ok, thank you for explaining further. Is this behavior always tied to the `odometer` value? I can't test myself against a low mileage vehicle.
> 
> If you want to put together a PR to address this I can review/merge it in.

I think you're still a little unclear.
My car's on 35k, this scenario applies to all cars but the logic won't work on cars with less than 360 miles as you can't differentiate between a heading or odo.  On cars with more than 359 miles (I've corrected my logic) then the logic works:
If the 2nd value after the timestamp is GT 359 then it must be mileage, ELSE it is a heading

(359 being the largest value heading can contain before reverting to 0)

I'm happy to close this issue without remediation as there's no 100% reliable solution that's obvious to me.

**Comment by mseminatore** [comment]
OK. If you do decide that there is a reasonable solution please re-open and we can see about addressing.

**Comment by IMgoRt** [comment]
> OK. If you do decide that there is a reasonable solution please re-open and we can see about addressing.

I don't know why I couldn't see this logic previously:
```
shift_state must be either null, D, P or R
if it's a number then the fields are in the wrong order so adjust
```
Thanks
