### ISSUE TITLE
Streaming disconnected

### ISSUE THREAD

**Issue by rileymd88** [mseminatore/TeslaJS#215]
**Describe the bug**
Whenever I try to connect to the streaming API I get `Error: disconnected`. I also tried making a connection myself without this library and got the same message so maybe it is a general problem.

**Steps To Reproduce**
Identify the steps to reproduce the behavior:
Run the following code:
```
var tjs = require('teslajs');
var streamingOptions = {
    vehicle_id: vehicleId,
    authToken: authToken
};
tjs.startStreaming(streamingOptions, function (error, response, body) {
    if (error) {
      console.log(error);
      return;
    }
    // display the streaming results
    console.log(body);
    console.log("...Streaming ended.".cyan);
  });
```

**Expected behavior**
A connection to the streaming API should be made

**Library version**
4.9.5

**Additional context**
- Tested with a Model 3 LR on 2020.48.12.1
- Tested while charging at home
- Also tried to stop charging and to turn on climate while connecting to change streaming values

**Update**
I managed to get one `data:updated` message using my own code byresending the `subscribe_oauth` message. Perhaps it would make sense to add this logic into teslajs? My sample code is here:
```
  const options = {
    "vehicleId": "123456789",
    "authToken": "1234567891011121314"
}
  const streamingColumns = ['elevation', 'est_heading', 'est_lat', 'est_lng', 'est_range', 'heading', 'odometer', 'power', 'range', 'shift_state', 'speed', 'soc']
  const streamingUrl = `wss://streaming.vn.teslamotors.com/streaming/`
  const ws = new WebSocket(streamingUrl, {
    perMessageDeflate: false
  })
  ws.on('message', function (data) {
    const d = JSON.parse(data)
    console.log(d)
    if (d.msg_type === 'control:hello') {
      ws.send(JSON.stringify({
        msg_type: 'data:subscribe_oauth',
        token: options.authToken,
        value: streamingColumns.join(','),
        tag: options.vehicleId.toString()
      }));
    }
    if (d.msg_type === 'data:error') {
      ws.send(JSON.stringify({
        msg_type: 'data:subscribe_oauth',
        token: options.authToken,
        value: streamingColumns.join(','),
        tag: options.vehicleId.toString()
      }));
    }
  })
```

**Comment by mseminatore** [comment]
Did you try the streaming sample?

**Comment by rileymd88** [comment]
Hi @mseminatore 

I tried the streaming sample and get the same error:
```
Vehicle MYVIN - Model 3 ( 'Steve' ) is: ONLINE

Note: Inactive vehicle streaming responses can take up to several minutes.

Streaming starting...
Columns: timestamp,elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc
Error: disconnected
Websocket disconnected
```

**Comment by rileymd88** [comment]
Found out some more information today by looking around: https://forum.abetterrouteplanner.com/topic/2250-abrp-losing-connection-to-battery-status/page/2/?tab=comments#comment-6961

I was also using Teslamate which also uses the streaming API. I guess it appears that if you are using another service like this it can cause the error in this issue. I tried stopping Teslamate and trying my code again and it worked.

**Comment by mseminatore** [comment]
When I run the sample I get back one response and then it disconnects. This is typical of a parked car that his sleeping or hibernating (as mine is).

Vehicle <vin>- Model S ( 'Electra' ) is: ONLINE

Note: Inactive vehicle streaming responses can take up to several minutes.

Streaming starting...
Columns: timestamp,elevation,est_heading,est_lat,est_lng,est_range,heading,odometer,power,range,shift_state,speed,soc
{
  msg_type: 'data:update',
  tag: '2010246753',
  value: <redacted>
}
...Streaming ended.
Error: disconnected

**Comment by rileymd88** [comment]
So this issue has gone away now. The only thing that changed was that I got an update from `2020.48.12.1` to `2020.48.26`
