### ISSUE TITLE
integration of Powerwall possible?

### ISSUE THREAD

**Issue by marlan99** [mseminatore/TeslaJS#244]
Like the data for the cars there are maybe also data for the powerwall available?

**Comment by mseminatore** [comment]
Are the Powerwall API's documented somewhere? If so please share a reference. They may be easy to add.

Note that I do not have a Powerwall so am unable to test or validate.

**Comment by mseminatore** [comment]
Tesla has once again broken 3rd party auth so I am not able to investigate this request further at this time.

**Comment by mseminatore** [comment]
Tesla has removed the Captcha requirement so the library is working. However, I still have no access to a Powerwall for testing. Nor a reference for any of the Powerwall API's. I'm going to close this now. If you can point me to some resources please feel free to comment and I can try to take a look.
