### ISSUE TITLE
Can Chinese users use it? Login error!

### ISSUE THREAD

**Issue by lylus** [mseminatore/TeslaJS#245]
I'm a Chinese user. I need to jump to auth.tesla.cn to view the API documents.

I use my China regional account to execute the following command, which shows the following error.

`cd samples`
`node login.js user@user.com password`

`Error: No authorization code issued; credentials likely incorrect`
    `at /TeslaJS/src/auth.js:100:19`
    `at tryCallOne (/TeslaJS/node_modules/promise/lib/core.js:37:12)`
    `at /TeslaJS/node_modules/promise/lib/core.js:123:15`
    `at flush (/TeslaJS/node_modules/asap/raw.js:50:29)`
    `at processTicksAndRejections (node:internal/process/task_queues:78:11)`

or

`Error: Login credentials rejected`
    `at /usr/node_modules/teslajs/src/auth.js:93:19`
    `at tryCallOne (/usr/node_modules/teslajs/node_modules/promise/lib/core.js:37:12)`
    `at /usr/node_modules/teslajs/node_modules/promise/lib/core.js:123:15`
    `at flush (/usr/node_modules/teslajs/node_modules/asap/raw.js:50:29)`
    `at processTicksAndRejections (node:internal/process/task_queues:78:11)`

The credentials have been confirmed to be error free

**Comment by mseminatore** [comment]
It is my understanding that the auth flow is different for users in China. I have no way to test or validate that so am unable to add support for it. Perhaps someone else will send a PR that adds support in a compatible way.
