### ISSUE TITLE
Logout does not remove the token

### ISSUE THREAD

**Issue by just4give** [mseminatore/TeslaJS#250]
Has anyone tried to revoke a token? I called logout function which returned 200 response but token is still active. I even tried https://owner-api.teslamotors.com/oauth/revoke directly but that does not work either. Wondering if I am doing something wrong.

**Comment by mseminatore** [comment]
Historically Tesla did not (properly from an OAuth perspective) honor requests to revoke the token. So the TeslaJS library simply deleted the cached .token file if it existed.

The only reliable way that I know of to invalidate an existing token is to change the Tesla.com password.

**Comment by just4give** [comment]
Thanks @markseminatore ... will try that :)
