### ISSUE TITLE
Add support for 4.1.0 endpoints

### ISSUE THREAD

**Issue by normanmaurer** [mseminatore/TeslaJS#282]
See https://github.com/timdorr/tesla-api/commit/17500b0d64dcbbe34949dddc007e4399df531a3d

**Comment by GaPhi** [comment]
I have added setChargingAmps, setScheduledCharging, setScheduledDeparture API calls (but not tested yet) in my forked project. If someone wants to try it and merge in master branch...

**Comment by GaPhi** [comment]
My pending pull request has been updated with those new API calls (removing my auth token patch).

**Comment by mseminatore** [comment]
@normanmaurer @GaPhi I believe this has now been addressed with the PR merges of today. Please let me know if that is not the case.
