### ISSUE TITLE
Charge Current update in API

### ISSUE THREAD

**Issue by TomNijsen** [mseminatore/TeslaJS#286]
Finally we can now modify the charge current through the Tesla app. It would be nice to also have this functionality in the API, so we could use it in our NodeRED flows to allow the EV charging to follow the solar excess availability.

Thanks for your great work!

**Comment by TomNijsen** [comment]
Perfect, looking forward to test it in my NodeRED script of #KermtStroomt!

**Comment by GaPhi** [comment]
I proposed a pull request for 3 new api calls including this one.
Already merged in Nodered, but it needs the merge here to be effective in Nodered...

**Comment by GaPhi** [comment]
The 3 new API are now fully tested/debugged with GaPhi/TeslaJS and GaPhi/node-red-contrib-tesla forks, waiting for the last merges into original branches.

**Comment by mseminatore** [comment]
@TomNijsen @GaPhi I believe this has now been addressed with the PR merges done today. Please let me know if that is not the case.
