### ISSUE TITLE
Access Tokens only valid for 8 hours

### ISSUE THREAD

**Issue by joepalexander** [mseminatore/TeslaJS#291]
Not an issue with this brilliant framework. But is this an issue everyone else is having? and has anyone conjured up a solution for it? I can generate my Tesla access tokens, however they used to be available for 30 days, it is now only available for 7 hours? 

Any light on this anyone please

**Comment by mseminatore** [comment]
@joepalexander I think you have to trade in the 7 hour token for the 30 day token as one of the steps. How are you acquiring the 7 hour token?

**Comment by tonybroadbent** [comment]
Same problem here.  I am using the IOS app 'Auth for Tesla'.  Does anyone have a better way of getting a longer token cause 7 hours just isn't enough!

**Comment by IMgoRt** [comment]
> Same problem here. I am using the IOS app 'Auth for Tesla'. Does anyone have a better way of getting a longer token cause 7 hours just isn't enough!

https://github.com/adriankumpf/tesla_auth

**Comment by joepalexander** [comment]
@mseminatore through auth app on iOS. Is there a better/new option? 
Since starting work as a data engineer I rarely find time to work on my personal projects so it all escaped me so quickly 😩

**Comment by joepalexander** [comment]
@IMgoRt I tried the Tesla_auth and it still comes back as _valid for 8 hours_... Could this be the end of the 30 day access tokens? Thoughts @mseminatore?

**Comment by IMgoRt** [comment]
> 

There's an option to produce the 45 day refresh token

**Comment by joepalexander** [comment]
@IMgoRt YOU ABSOLUTE STAR YOU! Proof that not reading the docs can be detrimental! _-o_ flag yielded me a 45 day access token. Crisis averted. @mseminatore Could the web view access token grabbing method be added into the login function? Is that something that would be possible?
