### ISSUE TITLE
4.10.0 release missing on npm

### ISSUE THREAD

**Issue by normanmaurer** [mseminatore/TeslaJS#295]
Seems like the latest version wasn't published to npm yet:
https://www.npmjs.com/package/teslajs

Would be nice to be able to have 4.10.0 there.

**Comment by GaPhi** [comment]
I have published @gaphi/node-red-contrib-tesla for my personal needs of
this can help you, before returning to the main branch when all the
packages will be available...

Le ven. 31 déc. 2021 à 18:12, Norman Maurer ***@***.***> a
écrit :

**Comment by mseminatore** [comment]
It is now published.
