### ISSUE TITLE
Sample login.js return 403..

### ISSUE THREAD

**Issue by vbarrier** [mseminatore/TeslaJS#317]
**Describe the bug**
I tested with 2 different accounts and on multiple IPs.

**Steps To Reproduce**
Identify the steps to reproduce the behavior:
1.  node login.js vincent@****** ********
2. Login credentials rejected

```
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;authorize&#63;" on this server.<P>\n` +
    'Reference&#32;&#35;18&#46;a15d645f&#46;1648403146&#46;32e72b1\n' +
```

**Comment by mseminatore** [comment]
Tesla has broken logins and unfortunately I have not yet been able to fix it.

**Comment by vbarrier** [comment]
Ok thank you for the quick reply!

**Comment by vbarrier** [comment]
Hello ! 
Why did you close the issue? Does it work now? 
I still get an error when trying to login with the lib.

**Comment by mseminatore** [comment]
This is a duplicate of #261. At this time there is no known workaround to fix the library.
