### ISSUE TITLE
Getting "Error: Login credentials rejected" despite being able to login to my account on Tesla.com?

### ISSUE THREAD

**Issue by klinquist** [mseminatore/TeslaJS#352]
**Describe the bug**

Hi Maintainers,

I've got a Model 3.  I can manage it from Tesla.com; however, when I use this nodejs module with the same email & password, I get `Error: Login credentials rejected`.   MFA is not enabled.   Tried in my own code & the cli-based tool in the `samples` folder.  

![Screenshot-2023-07-16-09 26 03](https://github.com/mseminatore/TeslaJS/assets/1343376/c87fe127-9a66-41bb-bcfd-8c9793d43350)

Any ideas?  Looks like this hasn't been maintained in awhile?

**Comment by mseminatore** [comment]
In 2021 Tesla broke login via this, and many other libraries, by introducing a required a reCaptcha step for login. We have not yet been able to fix this issue.

**Comment by klinquist** [comment]
Thanks, I was able to obtain an accessToken/refreshToken by logging in (and completing the captcha) as part of https://github.com/adriankumpf/tesla_auth

From there, I just refresh the token prior to making any request.   Working now!
