### ISSUE TITLE
Location information missing since upgrade vehicle software to 2023.38.x

### ISSUE THREAD

**Issue by paede81** [mseminatore/TeslaJS#354]
After Model 3 upgraded to 2023.38.x I noticed, that drive_state object is now missing the elements latitude and longitude.

It seems like, Tesla changed the API. According to this post: https://github.com/onokje/node-red-contrib-tesla/issues/69#issuecomment-1826843669 
This change will work as a workaround:

**From:**
https://github.com/mseminatore/TeslaJS/blob/dc4ad635518c502990a3bb0b203e7f59fa72d047/teslajs.js#L760

**To:**
`get_command(options, "vehicle_data?endpoints=location_data%3Bcharge_state%3Bclimate_state%3Bclosures_state%3Bdrive_state%3Bgui_settings%3Bvehicle_config%3Bvehicle_state", callback);`

**Comment by paede81** [comment]
Any updates?

**Comment by mseminatore** [comment]
The library development is currently on hold as we are unable to authenticate with the Tesla servers.
