### ISSUE TITLE
Server run file

### ISSUE THREAD

**Issue by zerocooling** [mseminatore/TeslaJS#358]
Where is the file so that I start node js server ?
Thank you

**Comment by mseminatore** [comment]
TeslaJS is a library, not a server application. Several example apps are provided that can be run under Node.

**Comment by zerocooling** [comment]
Thank you for answering me quickly.


I came out the errors, when I run login.js

Error: Cannot find module 'colors'

Do you know how I can solve this problem ?

**Comment by mseminatore** [comment]
Did you read the documentation about installing dependencies?

To install dependencies via npm, from the root level of the library directory type:

npm install

**Comment by zerocooling** [comment]
thank you
