### ISSUE TITLE
login.js error

### ISSUE THREAD

**Issue by zerocooling** [mseminatore/TeslaJS#360]
I got this error.
I put the account email, password, and mfa.
C:\tesla\node_modules\teslajs\samples>node login.js zeroco***  *** *****
Error: Login credentials rejected
    at C:\tesla\node_modules\teslajs\src\auth.js:96:19
    at tryCallOne (C:\tesla\node_modules\teslajs\node_modules\promise\lib\core.js:37:12)
    at C:\tesla\node_modules\teslajs\node_modules\promise\lib\core.js:123:15

**Comment by mseminatore** [comment]
Unfortunately, Tesla has broken the library authentication (by introducing a full browser / captcha requirement) and I've not yet found a reliable workaround.

**Comment by SkyLostTR** [comment]
So this library is not working anymore?

**Comment by mseminatore** [comment]
> So this library is not working anymore?

Yes, that is correct. Tesla has broken authentication and an acceptable solution has not been identified. If you are able to acquire a valid token through other means, the library should work.

**Comment by zerocooling** [comment]
btw tesla has an apple watch app , that control the car.

2025년 5월 9일 (금) 오전 9:49, Mark Seminatore ***@***.***>님이 작성:
