### ISSUE TITLE
adding colors creates uncaught exceptions

### ISSUE THREAD

**Issue by roopesh** [mseminatore/TeslaJS#49]
For example, if the call is a failure, line 282
`log(API_RESPONSE_LEVEL, "\nResponse: " + JSON.stringify(response).magenta);`
causes the server to crash.  I'd say remove all the colors completely or at least anything that could fail.

**Comment by mseminatore** [comment]
What server environment are you using?  This library is in continual use across multiple Azure and AWS services with logging set at various levels without issue.

That said it is clear that colors are not needed in server logging so I am not opposed to removing it in a future update.

**Comment by mseminatore** [comment]
@roopesh Addressed in **2.0.21** by removing `colors` dependency from TeslaJS.js.  While useful for debugging it was not needed and was reported as causing some issues with server use cases.

**Comment by roopesh** [comment]
Thanks!
