### ISSUE TITLE
npm install putting main project in node_modules

### ISSUE THREAD

**Issue by TrevorPT** [mseminatore/TeslaJS#59]
Hello! I followed the basic instructions `npm install teslajs` and it creates a folder `node_modules` which contains all of the dependent modules as well as the subfolder `teslajs`.  I then must go within there and perform `npm install` to get the dependencies under the teslajs project folder.  Am I doing something wrong or is the hierarchy backwards on install using npm?

**Comment by mseminatore** [comment]
Hey @TrevorPT Are you just trying to play with the library or are you trying to build a project that includes the library?  If the former then the instructions are correct.  You first install `teslajs` and then you must install it's dependencies.

**Comment by TrevorPT** [comment]
Hey, thanks for the response. Nice little project you have! At this point I'm just playing around with the library, but it doesn't seem to be installing in the place where I expected it to go.  

After `npm install teslajs` I get `\teslajs\node_modules` which contains 66 folders including `teslajs`.  At first I thought these were the dependencies.

`\teslajs\node_modeules\teslajs` contains the project files (I expected them in the root `\teslajs`) and I then ran `npm install` to get the dependencies which end up in `\teslajs\node_modules\teslajs\node_modules`.  

I guess the actual question should be: what are all the dependencies for in the root `\teslajs\node_modules`? Or are they libraries you are using in your own project?

It's not really causing any problems, it just didn't install the project files (like `package.json`) where I was expecting them so I thought I'd report it; it may be, though, that I've misunderstood your structure.

**Comment by mseminatore** [comment]
@TrevorPT  I see now what you are saying.  The way that `npm` works is that it assumes that you are installing package(s) as part of your own project.  So when you `npm install teslajs` it is going to create a `node_modules` in your current dir and install `teslajs` and **all of it's dependencies** in a `node_modules` underneath `teslajs` 

At this point your folder structure will look something like this:

`.../your_root_folder/node_modules/teslajs/node_modules`

This is fine, to play around with `teslajs` simply cd into the `teslajs/examples` folder and try out some of the samples.

**Comment by TrevorPT** [comment]
Ahh, thanks for the explanation. We played with some of the examples. I see now where I went wrong ... I was thinking of TeslaJS as a primary project, not as a library (which it is, of course).  I think what threw me were the two levels of dependencies.  Thanks! Not an issue, closing.
