### ISSUE TITLE
simpleStreaming.js doesn't seem to work

### ISSUE THREAD

**Issue by TrevorPT** [mseminatore/TeslaJS#61]
We're interested in finding out more about data available for streaming.  

First, if I use simpleStreaming.js as shown in the "usage": `simpleStreaming -p <password> username`
all it does is show me the "Usage" message and it doesn't seem to be attempting to log in.  Should the username be an option? ie. add this line? 
```javascript
  .option('-u, --username [string]', 'username (needed only if token not cached)')
```

Second, get_command uses
```javascript
headers: { Authorization: "Bearer " + options.authToken, 'Content-Type': 'application/json; charset=utf-8'}
```

It looks like `function startStreaming` uses an `auth` member in req and not a header token from the .token file; is this work in progress or is the API different for streaming? 

When we tried streaming the other day (with a valid login .token, which I do not have available at the moment) it kept failing with a message about "no authentication mechanism".  

If it's working for you, I will attempt to reproduce it and get more details. Thanks!

**Comment by mseminatore** [comment]
@TrevorPT The Tesla provided streaming API works very differently from the other APIs.  You log in to the streaming portal using the username and a "token" that is returned from the vehicles() call.  

I find and fix an issue with the sample that was related to the migration to the sample framework.  If you can update to the latest please try the sample again.  And note that for a parked vehicle the streaming results can take up to several **minutes** to return.

**Comment by TrevorPT** [comment]
@mseminatore Updated to latest (2.1.16) and confirmed it works now. Thanks!

The function `startStreaming` -- by the name it seems to imply that it starts a continuous data streaming process, but looking at the code it only makes one request and (presumably) gets one response. Is that correct? So it does not start actually streaming the data continuously, it has to be polled? Also, I didn't find the docs on the streaming API on https://github.com/timdorr (other than looking at stream.rb); is it found elsewhere?

**Comment by mseminatore** [comment]
@TrevorPT Did you try it?  If the car is parked you should receive ~2 responses before the connection closes.  If the car is moving you should many at a rate of one every ~250ms.  

The way that Tesla seems to have implemented streaming is as a long-lived http socket connection.

**Comment by mseminatore** [comment]
@TrevorPT Regarding API documentation you will want to consume and follow this thread: https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-93#post-1933566

**Comment by TrevorPT** [comment]
Thanks for clarifying. I did try it but only when parked so only got two records.  Just reading the code I wasn't sure if there was some kind of keep-alive in effect, and I suppose now that if the car is parked the Tesla server is optimized to kill the connection and not waste bandwidth. Thanks for the pointer to the API thread.
