### ISSUE TITLE
Add refresh token support

### ISSUE THREAD

**Issue by DoctorMcKay** [mseminatore/TeslaJS#74]
When authenticating, in addition to sending back a bearer token, the Tesla API also sends a refresh token. This refresh token can be used with the same authentication endpoint (`https://owner-api.teslamotors.com/oauth/token`) by setting `grant_type` to `refresh_token` and also sending the refresh token as a `refresh_token` parameter. The response is identical to password authentication (and it includes a new refresh token, which invalidates the old one).

[More here](https://tools.ietf.org/html/rfc6749#page-47)

**Comment by mseminatore** [comment]
Could you elaborate a little bit more on what you would like to see?  For example, are you asking for the samples to write the token/refresh_token into the cache file?  Or are you asking for that extra data to be returned from `login()`?  Or something else.

**Comment by DoctorMcKay** [comment]
It doesn't seem that there is any method that consumes a refresh token to return a bearer token. Would be nice for that to be added.

**Comment by mseminatore** [comment]
You are right that there is currently no method that consumes a refresh_token.  However it should not be difficult to add.

The `login()` method already returns the full response body from the REST call.  The returned body object looks like:

```
{
"access_token": "xxx", "token_type": "bearer", "expires_in": "3888000", "refresh_token": "xxx", 
"created_at": "xxx"
}

```

The main task is saving the data and a new method to consume it.

**Comment by DoctorMcKay** [comment]
Yes, I'm already using my own solution, but it would be nice to have proper library support.

```js
	log("Obtaining new bearer token...");
	Request.post({
		"uri": "https://owner-api.teslamotors.com/oauth/token",
		"form": {
			"grant_type": "refresh_token",
			"client_id": "snip",
			"client_secret": "snap",
			"refresh_token": refreshToken
		},
		"json": true,
		"gzip": true
	}, (err, res, body) => {
		// things
	});
```

**Comment by mseminatore** [comment]
OK.  Seems easy enough to add.  What would you want to call the new method?

**Comment by mseminatore** [comment]
OK I think I was able to add this without breaking anything.  The `login` sample now upgrades the saved token to the full login response body so the refresh token is available.  The sampleFramework recognizes old vs. new cached token format and handles appropriately.

Please try out **2.1.24** and see if this meets your needs.

In the future please feel free to fork and send a PR.

**Comment by DoctorMcKay** [comment]
:+1: All looks good, seems to work. You may want to break the `refresh_token` property out of the `body` string and promote it to a top-level property. Using the refresh_token grant invalidates the token that's used and issues a new one (in addition to a bearer token).

**Comment by mseminatore** [comment]
Just to be clear, do you mean as a top level properly in the return from the `login()` call?  If so that is easy enough and non-breaking.

**Comment by DoctorMcKay** [comment]
Preferably both `login()` and `refreshToken()`, yes.

**Comment by mseminatore** [comment]
See **2.1.25**

**Comment by DoctorMcKay** [comment]
:+1: Cool, thanks.
