### ISSUE TITLE
Homelink example script arguments and documentation appear incorrect

### ISSUE THREAD

**Issue by DoctorMcKay** [mseminatore/TeslaJS#84]
As best I can tell, the homelink example script does not use the --name argument which it requests with the description asking for a phone Bluetooth name. This appears to be copied from the calendar script. If this is indeed not used, it should probably be removed from the script and documentation.

**Comment by mseminatore** [comment]
Yes, that does appear to be a copy error.  Thanks for catching.

**Comment by DoctorMcKay** [comment]
Thanks! Shall I close this or will you take care of that?

**Comment by mseminatore** [comment]
I'll close!  Thanks again.
