### ISSUE TITLE
How to use streaming-api

### ISSUE THREAD

**Issue by steam0** [mseminatore/TeslaJS#87]
### Problem
I want to use the streaming features, but I see no examples to how I would code it. I don't know what a streaming server should be? Is it perhaps a kafka server?

Could you please provide a short guide or tutorial?

**Comment by mseminatore** [comment]
Have you already looked at the [simpleStreaming ](https://github.com/mseminatore/TeslaJS#simplestreamingjs)sample that comes with TeslaJS?

**Comment by steam0** [comment]
Yes, all I see is that the program waits for data, and suddenly it is just "done" and show me a couple of lines from the stream.

What is the stream server supposed to do?  What kind of server can receive this? Any examples?

**Comment by mseminatore** [comment]
The sample shows how the Tesla streaming API works.  You call it and it opens a streaming connection.  When/if data is available from Tesla the callback will be called with the data.  When the car is not moving the data is limited and the connection will close.
