### ISSUE TITLE
Does Homelink API work? I am getting 400

### ISSUE THREAD

**Issue by mohamedmansour** [mseminatore/TeslaJS#92]
On my Model 3 with Auto Pilot, all other commands work great. The only command that doesn't work is Homelink which is returning a 400 response. Can someone please sniff Tesla Model S app for Homelink if the command is still `command/trigger_homelink` ?

**Comment by mseminatore** [comment]
No, unfortunately I've not been able to get the homelink API to work.  I usually received a 200 but the doors did not activate.  Is there a status message with the 400 response?

**Comment by mohamedmansour** [comment]
@mseminatore  I will check tonight, the error callback you exposed with (error, result) error was just a number 400 and result was just null. I will look deeper tonight!

**Comment by cgalpin** [comment]
Here is what I am getting. Model 3 w/ AP and FSD

REQUEST response end https://owner-api.teslamotors.com/api/1/vehicles/[redacted]/command/trigger_homelink 400 { server: 'nginx',
  date: 'Sat, 25 Aug 2018 15:46:21 GMT',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '66',
  connection: 'close',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'cache-control': 'no-cache',
  'x-request-id': '941bdb0c-88f4-45d6-87b1-2a325d0a66ab',
  'x-runtime': '0.010533' }

**Comment by mseminatore** [comment]
Thanks.  This still remains an open issue.  I think the endpoint has been removed and Summon must be used.  Unfortunately I don't have an AP-enabled vehicle to test on.

**Comment by DoctorMcKay** [comment]
Some time ago I reverse-engineered the Summon API to try to work out how to trigger HomeLink. I got it to the point where it will respond with `no_homelink_nearby` but I don't have a door with which to test it (yet).

https://github.com/DoctorMcKay/node-tesla-data/blob/master/tesladata.js#L521

**Comment by focher** [comment]
I know this is old, but I've been trying to add Homelink support to NFarina's Homebridge plug-in, and struggled with it.

For sure, the API call is there as I can perform it using Postman. It's actually very straightforward.

**URL**
https://owner-api.teslamotors.com/api/1/vehicles/[id]/command/trigger_homelink

**Body**
`{
    "lat": [latitude of the car as a number],
    "lon": [longitude of the car as a number]
}`

I've seen some API references call for some type of token as a third attribute, but this is not necessary.

I believe the current homelink function in the library needs to be adjusted to fit this, as when I use the API call in the library I get back a "too far away" result.

**Comment by focher** [comment]
Just a quick summary of the code changes I manually made to get the library call for Homelink to work.

`
exports.homelink = function homelink(options, lat, long, callback) {
    post_command(options, "command/trigger_homelink", { lat: lat, lon: long } , callback);
`

So I removed the token and change the name of the Longitude attribute to "lon". The API call then worked.

**Comment by mseminatore** [comment]
Thank you @focher that is a good catch. However, when I try this fix I still get "no_homelink_nearby" - I made sure to wake the car up first. Any ideas?

**Comment by focher** [comment]
> Thank you @focher that is a good catch. However, when I try this fix I still get "no_homelink_nearby" - I made sure to wake the car up first. Any ideas?

Can you pull the vehicle_data and see what the "homelink_device_count" and "homelink_nearby" values are in the "vehicle_state" segment? The first must obviously be a 1 (that confirms Homelink is supported by the car) and the second one must be true, which means the car's location is close enough to the lat and lon values sent in the API call.

I'm setting the "lat" and "lon" values to the same as the car shows in the "drive_state" segment when making the call.

**Comment by mseminatore** [comment]
I am using the homelink.js sample which uses the GPS values from `drive_state` and passes them to homelink.

**Comment by mseminatore** [comment]
Looking at `vehicle_state` I do not see any properties related to homelink. My car is a pre AP vehicle.

    "api_version":8,
    "car_version":"2020.24.6.11 3f9850467abb",

**Comment by mseminatore** [comment]
@focher Another property of interest is:

"native_type": "wgs"

Does that match what you are seeing?

**Comment by focher** [comment]
Yep.

        "drive_state": {
            "gps_as_of": 1596743162,
            "heading": 87,
            "latitude": [latitude value],
            "longitude": [longitude value],
            "native_latitude": [home latitude],
            "native_location_supported": 1,
            "native_longitude": [home longitude],
            "native_type": "wgs",
            "power": -7,
            "shift_state": null,
            "speed": null,
            "timestamp": 1596743804100
        },

I believe the Tesla API will not accept the Homelink command if the LAT and LON you are passing are not within proximity to the native_latitude and native_longitude values. I think (but do not know) that the backend wants to confirm the car is close enough to the Homelink device but obviously has to trust what is passed to it. The API is only cross-checking what is sent to whether it's close enough to your "home" location set in the car.

**Comment by focher** [comment]
Here's the cURL call:

curl --location --request POST 'https://owner-api.teslamotors.com/api/1/vehicles/[id]/command/trigger_homelink' \
--data-raw '{
    "lat": [latitude],
    "lon": [longitude]
}'

**Comment by mseminatore** [comment]
You are on API v9 so perhaps that is the difference. I am passing in the GPS value returned by the car, but maybe my car thinks my home is in another location? I'll check that.

**Comment by focher** [comment]
I can confirm that the code change works! Thanks so much for such a great library! I'll be hopefully enhancing the Homebridge plugin to include Homelink once the new version of the API library is available.

**Comment by ArthurD** [comment]
FWIW, I can also confirm that the latest code has Homelink working for me when used against a 2018 Model S w/ FSD.

**Comment by mseminatore** [comment]
I believe this is now resolved.
