### ISSUE TITLE
Streaming API Broken after Model 3 updated to 2018.18.3 04dfd3c

### ISSUE THREAD

**Issue by seeARMS** [mseminatore/TeslaJS#93]
### Expected behavior
The streaming API works as intended, and returns updates every ~250 msec.

### Actual behavior
The streaming API connects successfully, but does not return anything regardless of the state of the Model 3 (awake, driving, etc - nothing is returned).

### Steps to reproduce the behavior
This started as soon as my Model 3 updated to version 2018.18.3 04dfd3c. Streaming was working before that, then immediately after the update, it began returning nothing. I've restarted the car, restarted the server, tried across several different days, and the streaming API continues to return nothing.

### Version of the library tested
Latest version as of https://github.com/mseminatore/TeslaJS/commit/6baeab9da999546c4a8f06f7b1864b39d9c14b20

**Comment by mseminatore** [comment]
Looking into this one over the weekend.  I just merged in your older PR.

**Comment by viperx77** [comment]
I'm new here but would like to contribute.  Just tried simpleStreaming.js on my Model 3 and am getting output of undefined. All other samples work. Not sure if this is the same behavior.

**Comment by mseminatore** [comment]
@viperx77 @seeARMS I've been seeing reports that Tesla disabled the streaming interface for M3 vehicles.  I am not on the later updates and will test with my MS.

**Comment by DoctorMcKay** [comment]
The latest version of the Tesla app appears to stream data over WSS. It connects to `wss://streaming.vn.teslamotors.com/streaming/`. Once a connection is established, it sends a TEXT frame with this JSON payload:

```json
{
    "tag": "<vehicle_id as a string>",
    "token": "<some token value I haven't found yet>",
    "value":"shift_state,speed,power,est_lat,est_lng,est_heading,est_corrected_lat,est_corrected_lng,native_latitude,native_longitude,native_heading,native_type,native_location_supported",
    "msg_type":"data:subscribe"
}
```

The server responds with only BINARY frames, which contain UTF-8 encoded JSON. The first response frame contains:

```json
{
    "msg_type": "control:hello",
    "connection_timeout": 0
}
```

The next and presumably subsequent frames contain:

```json
{
    "msg_type": "data:update",
    "tag": "<vehicle_id as a string>",
    "value": "1552546831409,,,0,redacted,redacted,179,redacted,redacted,redacted,redacted,179,wgs,1"
}
```

The first value in the comma-separated string appears to be the Unix time in milliseconds, with the remaining values corresponding to the values we requested.

When the app disconnects, it first sends a TEXT frame containing:

```json
{
    "tag": "<vehicle_id as a string>",
    "msg_type": "data:unsubscribe"
}
```

Then it sends a CLOSE frame. I will update as soon as I figure out what token it's using.

**Comment by DoctorMcKay** [comment]
Update: The token is your Tesla account email address concatenated with `:` and the first token in the `tokens` array in vehicle data, encoded in UTF-8, then base64'd. So in Node: `Buffer.from(email + ':' + data.tokens[0], 'utf8').toString('base64')`.

**Comment by tanglewood16** [comment]
Hi @DoctorMcKay Did that work for you? I have tried the exact same scheme for the last two months periodically, but could never get it to work with my Model 3. I do get the 'Hello' message, but the next message is always

`{"msg_type":"data:error","tag":<vehicle_id>,"value":"disconnected","error_type":"vehicle_disconnected"}`

Am I missing something?

**Comment by DoctorMcKay** [comment]
@tanglewood16 It does in fact seem to work for me, using this code:

```js
const WS13 = require('websocket13');

let ws = new WS13.WebSocket("wss://streaming.vn.teslamotors.com/streaming/");
ws.on('connected', function() {
	console.log('connected');
	ws.send(JSON.stringify({
		"tag": "redacted",
		"token": "redacted",
		"value": "shift_state,speed,power,est_lat,est_lng,est_heading,est_corrected_lat,est_corrected_lng,native_latitude,native_longitude,native_heading,native_type,native_location_supported",
		"msg_type": "data:subscribe"
	}));
});

ws.on('message', (type, data) => {
	console.log(data.toString('utf8'));
});

ws.on('disconnected', function() {
	console.log('disconnected');
	console.log(arguments);
});
```

**Comment by dturton** [comment]
Any update here? I am also getting `"error_type":"vehicle_disconnected"`

**Comment by tanglewood16** [comment]
Thanks @DoctorMcKay for your reply. My code did pretty much the same thing as yours, and I tried both ws and your websocket13, still no cigar. At first I thought perhaps I did something wrong with my "token" field, but then when I used a bogus value there, I got a message back telling me the credential was wrong, rather than "disconnected".

I don't know if this makes a difference: My Model3 is a Nov.'18 build, LR AWD. What is your build date and configuration?

**Comment by DoctorMcKay** [comment]
I have a Nov/Dec 2016 Model S. It might be different for Model 3, possibly.

**Comment by DoctorMcKay** [comment]
I just borrowed credentials from a friend who has a Model 3, and it seems that the same thing is happening when the app tries to connect on the location screen. It seems to me that maybe the streaming API is just broken for Model 3 right now. Can anyone with a Model confirm whether they get live updates of speed and location in the map view in the app when they're driving around?

**Comment by tanglewood16** [comment]
OK. That matched what I thought was the case-- the streaming service works for Model S and X, but not for Model 3.
