### ISSUE TITLE
Getting TypeError: Cannot read property 'access_token' of undefined when trying login.js

### ISSUE THREAD

**Issue by flexgames** [mseminatore/TeslaJS#95]
### Expected behavior
Login Successful

### Actual behavior
Throws error : `TypeError: Cannot read property 'access_token' of undefined`

### Steps to reproduce the behavior
install teslajs
switch to teslajs/Examples directory
node login.js (with myusername and mypassword as parameters)

error thrown

<img width="1017" alt="screen shot 2018-08-30 at 9 05 50 am" src="https://user-images.githubusercontent.com/2111634/44864380-59d1d200-ac34-11e8-9b9d-43863020e5a7.png">
### Version of the library tested
2.1.41

**Comment by mseminatore** [comment]
Thanks for the report.  I've heard that they may have changed the client keys.  I am investigating.

**Comment by inonprince** [comment]
adding this to the requests seems to do the trick:
```
headers: {
            'User-Agent': 'Mozilla/5.0 (Linux; Android 9.0.0; VS985 4G Build/LRX21Y; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36',
            'X-Tesla-User-Agent': 'TeslaApp/3.4.4-350/fad4a582e/android/9.0.0',
        }
```

**Comment by flexgames** [comment]
Thanks. Actually, manually adding the changes from @DoctorMcKay's PR today seems to fix what ails.

**Comment by DoctorMcKay** [comment]
Interesting that adding the headers seems to fix it. I just assumed that it was instead rejecting the x-www-form-urlencoded bodies but I honestly tried both at the same time and it worked, so I didn't dig any deeper.

**Comment by mseminatore** [comment]
Maybe part of the new security update is checking the headers more closely.  I am looking over the PR now and will merge if all the tests pass.

**Comment by mseminatore** [comment]
PR #96 merged into master.  NPM publish will happen shortly.

**Comment by SheldonLaw** [comment]
Get sample problem now.

**Comment by mseminatore** [comment]
@SheldonLaw You will need to provide more specifics if you need help.
