### ISSUE TITLE
Consolidate callback and promise functions

### ISSUE THREAD

**Issue by sean256** [mseminatore/TeslaJS#99]
Would it be possible to consolidate the callback and promise functions in a future version? If a callback function is not provided as an argument it could assume you want a promise back. It could greatly simplify documentation and clean things up a bit.

**Comment by mseminatore** [comment]
This sounds plausible though it would be a lot of work.  Feel free to prototype a solution and send a PR.  A simpler solution would be to offer only callbacks or promises.

**Comment by aparajita** [comment]
I'd suggest doing it the way Node does: `require('teslajs')` gives you the callback API, `require('teslajs').promises` gives you the Promise API. The actual function names would be the same; no need for the 'Async' variant of each function.

@mseminatore Just wondering, since this is advertised as a Node library, if you have any interest in modernizing the codebase to ES6. Node >= 8.1 supports const, native promises, async/await, destructuring, etc. I'd be interested in working on that if you're amenable.

**Comment by DoctorMcKay** [comment]
I just updated one of my Node modules to allow usage of either callbacks or Promises in the same function ([example](https://github.com/DoctorMcKay/node-steam-user/blob/master/components/account.js#L21)). It works pretty well; the only downside I've noticed so far is that if I use callbacks then my IDE whines at me about ignoring a returned promise.

**Comment by sean256** [comment]
Another option would be to ditch the callbacks all together in the next major version. Promises are the way of the future.

**Comment by mseminatore** [comment]
That's a possibility.  Not sure about forcing that change on everyone.  I'll take a look at @DoctorMcKay example and see how that looks.

**Comment by sean256** [comment]
> Not sure about forcing that change on everyone.

That's why you denote it as a major version change ;-)

**Comment by mseminatore** [comment]
@sean256 I get that, but it forces everyone to make potentially large changes to their codebase. Not very friendly for something that is not strictly required. I'll consider all the options.  I think the suggestion by @aparajita is interesting to consider.  That at least seems to provide some real value in return for the cost to users.

**Comment by jeffwilcox** [comment]
Happy to try and help with a modernization effort. Bonus points for TypeScript ;-) if it would add value.

Given where Node.js is in its LTS world, with Node 10.x being in LTS now, it's probably time to evolve and support that newer ES6+ world for a lot of reasons.

**Comment by foolip** [comment]
If anyone would like to try it or review it, I sent https://github.com/mseminatore/TeslaJS/pull/191 to show what a `require('teslajs').promises` solution might look like. I've tried using it myself for a very small thing, and it seemed to work.
